### PR TITLE
Fix broken Github link

### PR DESCRIPTION
**Pull request by peburrows**
Noticed this while clicking around today.

### CODE REVIEW

**Comment by welkie** [comment]
This affected me too. Note that your shouldn't include the protocol in links. In this case, it just needs to start with a forward slash.

**Comment by peburrows** [comment]
> Note that you shouldn't include the protocol in links

Not sure where you’re getting this, but links should absolutely include the protocol if the site you are linking to is available via https (as is the case here).

**Comment by welkie** [comment]
@peburrows Upon looking closer at that link, I realize now it goes to a different domain. I was confusing it with a link to a page on the same domain but at the root of the domain, where you'd just use a `/`. That's why I was suggesting omitting the protocol since I thought it was at the same domain.

I see nothing wrong wrong with this PR and it will fix the broken link.

**Comment by hvaara** [comment]
Great work!
@Strernd Would it be good to get this merged?

**Comment by Strernd** [comment]
Sorry I somehow completely missed the notifications! 
Great work, thanks!

**Pull request merged**
